<script setup lang="ts">
import { ref, watch, computed, onMounted } from 'vue';
import {
  VContainer, VCard, VCardText, VCardTitle, VTabs, VTab, VTabsWindow, VTabsWindowItem,
  VDataTable, VBtn, VDialog, VTextField, VCheckbox, VSelect,
  VSnackbar,
} from 'vuetify/components';
import {
  getMappingInstances, insertMappingInstance, updateMappingInstance, deleteMappingInstance,
  getListValues, insertListValue, updateListValue, deleteListValue,
  getMappingTypes, insertMappingType, updateMappingType, deleteMappingType,
  getShortcutGroups, insertShortcutGroup, updateShortcutGroup, deleteShortcutGroup,
} from '@/lib/db';
import type { MappingInstance, ListValue, MappingType, ShortcutGroup } from '@/lib/db';

const tab = ref('mappings');
const snackbar = ref(false);
const snackbarText = ref('');

const mappings = ref<MappingInstance[]>([]);
const listValues = ref<ListValue[]>([]);
const mappingTypes = ref<MappingType[]>([]);
const shortcutGroups = ref<ShortcutGroup[]>([]);

const refresh = async () => {
  [mappings.value, listValues.value, mappingTypes.value, shortcutGroups.value] = await Promise.all([
    getMappingInstances(),
    getListValues(),
    getMappingTypes(),
    getShortcutGroups(),
  ]);
};

const notify = (msg: string) => {
  snackbarText.value = msg;
  snackbar.value = true;
};

onMounted(refresh);

// ── Mapping instances ────────────────────────────────────────────────────────

const mappingDialog = ref(false);
const mappingForm = ref<{ id: number | null; name: string; expansion: string; implicit_add_base: boolean }>({
  id: null, name: '', expansion: '', implicit_add_base: false,
});

const openAddMapping = () => {
  mappingForm.value = { id: null, name: '', expansion: '', implicit_add_base: false };
  mappingDialog.value = true;
};

const openEditMapping = (row: MappingInstance) => {
  mappingForm.value = { id: row.id, name: row.name, expansion: row.expansion, implicit_add_base: row.implicit_add_base };
  mappingDialog.value = true;
};

const saveMapping = async () => {
  const { id, name, expansion, implicit_add_base } = mappingForm.value;
  if (!name.trim() || !expansion.trim()) return;
  if (id === null) {
    await insertMappingInstance(name.trim(), expansion.trim(), implicit_add_base);
  } else {
    await updateMappingInstance(id, name.trim(), expansion.trim(), implicit_add_base);
  }
  mappingDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteMapping = async (id: number) => {
  await deleteMappingInstance(id);
  await refresh();
  notify('Deleted');
};

const mappingHeaders = [
  { title: 'Name', key: 'name' },
  { title: 'Expansion', key: 'expansion' },
  { title: 'Add base', key: 'implicit_add_base' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

// ── List values ──────────────────────────────────────────────────────────────

/** Generate an abbreviation from a display value.
 *  Strategy: initials of each word → extend with more chars until unique for the type. */
function generateAbbreviation(value: string, typeId: string, excludeId: number | null): string {
  const taken = new Set(
    listValues.value
      .filter(v => v.type_id === typeId && v.id !== excludeId)
      .map(v => v.abbreviation.toLowerCase())
  );

  const words = value.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!words.length) return '';

  // Build candidate sequences: increase character budget until we find something unique
  // e.g. "Lisa Brown" → "lb" → "lib" → "libr" → "lisab" → ...
  const chars = words.map(w => w.replace(/[^a-z0-9]/g, '')).join('');

  // First try pure initials
  const initials = words.map(w => w[0] ?? '').join('');
  if (!taken.has(initials)) return initials;

  // Then try taking progressively more chars (spread across words first, then just extend)
  for (let budget = 2; budget <= Math.min(chars.length, 8); budget++) {
    // Distribute the budget across words
    let candidate = '';
    let remaining = budget;
    for (const word of words) {
      const take = Math.ceil(remaining / (words.length - words.indexOf(word)));
      candidate += word.slice(0, take);
      remaining -= take;
      if (remaining <= 0) break;
    }
    candidate = candidate.slice(0, budget);
    if (!taken.has(candidate)) return candidate;
  }

  // Fallback: initials + numeric suffix
  for (let i = 2; i < 100; i++) {
    const candidate = initials + i;
    if (!taken.has(candidate)) return candidate;
  }

  return initials;
}

interface ListValueForm {
  id: number | null;
  abbreviation: string;
  value: string;
  type_id: string;
  abbrevAutoGenerated: boolean;
}

const listValueDialog = ref(false);
const listValueForm = ref<ListValueForm>({
  id: null, abbreviation: '', value: '', type_id: '', abbrevAutoGenerated: true,
});

// True when abbreviation already belongs to a different row of the same type
const abbrevTaken = computed(() => {
  const { abbreviation, type_id, id } = listValueForm.value;
  if (!abbreviation || !type_id) return false;
  return listValues.value.some(
    v => v.type_id === type_id && v.abbreviation.toLowerCase() === abbreviation.toLowerCase() && v.id !== id
  );
});

// Auto-generate abbreviation while abbrevAutoGenerated is true
watch(() => listValueForm.value.value, (val) => {
  if (listValueForm.value.abbrevAutoGenerated) {
    listValueForm.value.abbreviation = generateAbbreviation(val, listValueForm.value.type_id, listValueForm.value.id);
  }
});

// Regenerate when type changes too (if still auto-generating)
watch(() => listValueForm.value.type_id, () => {
  if (listValueForm.value.abbrevAutoGenerated) {
    listValueForm.value.abbreviation = generateAbbreviation(
      listValueForm.value.value, listValueForm.value.type_id, listValueForm.value.id
    );
  }
});

const regenerateAbbrev = () => {
  listValueForm.value.abbreviation = generateAbbreviation(
    listValueForm.value.value, listValueForm.value.type_id, listValueForm.value.id
  );
  listValueForm.value.abbrevAutoGenerated = true;
};

const onAbbrevInput = () => {
  // User typed manually — stop auto-generating
  listValueForm.value.abbrevAutoGenerated = false;
};

const openAddListValue = () => {
  listValueForm.value = { id: null, abbreviation: '', value: '', type_id: '', abbrevAutoGenerated: true };
  listValueDialog.value = true;
};

const openEditListValue = (row: ListValue) => {
  listValueForm.value = {
    id: row.id,
    abbreviation: row.abbreviation,
    value: row.value,
    type_id: row.type_id,
    abbrevAutoGenerated: false, // existing value — don't auto-override
  };
  listValueDialog.value = true;
};

const saveListValue = async () => {
  const { id, abbreviation, value, type_id } = listValueForm.value;
  if (!abbreviation.trim() || !value.trim() || abbrevTaken.value) return;
  if (id === null) {
    await insertListValue(abbreviation.trim(), value.trim(), type_id.trim());
  } else {
    await updateListValue(id, abbreviation.trim(), value.trim(), type_id.trim());
  }
  listValueDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteListVal = async (id: number) => {
  await deleteListValue(id);
  await refresh();
  notify('Deleted');
};

const listValueHeaders = [
  { title: 'Abbreviation', key: 'abbreviation' },
  { title: 'Value', key: 'value' },
  { title: 'Type', key: 'type_id' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

// ── Mapping types ────────────────────────────────────────────────────────────

const typeDialog = ref(false);
const typeForm = ref<{ id: string; name: string; isEdit: boolean }>({ id: '', name: '', isEdit: false });

const openAddType = () => {
  typeForm.value = { id: '', name: '', isEdit: false };
  typeDialog.value = true;
};

const openEditType = (row: MappingType) => {
  typeForm.value = { id: row.id, name: row.name, isEdit: true };
  typeDialog.value = true;
};

const saveType = async () => {
  const { id, name, isEdit } = typeForm.value;
  if (!id.trim() || !name.trim()) return;
  if (isEdit) {
    await updateMappingType(id.trim(), name.trim());
  } else {
    await insertMappingType(id.trim(), name.trim());
  }
  typeDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteType = async (id: string) => {
  await deleteMappingType(id);
  await refresh();
  notify('Deleted');
};

const typeHeaders = [
  { title: 'ID (placeholder)', key: 'id' },
  { title: 'Name', key: 'name' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

// ── Shortcut groups ──────────────────────────────────────────────────────────

const groupDialog = ref(false);
const groupForm = ref<{ id: number | null; shortcode: string; expansion: string }>({
  id: null, shortcode: '', expansion: '',
});

const openAddGroup = () => {
  groupForm.value = { id: null, shortcode: '', expansion: '' };
  groupDialog.value = true;
};

const openEditGroup = (row: ShortcutGroup) => {
  groupForm.value = { id: row.id, shortcode: row.shortcode, expansion: row.expansion };
  groupDialog.value = true;
};

const saveGroup = async () => {
  const { id, shortcode, expansion } = groupForm.value;
  if (!shortcode.trim() || !expansion.trim()) return;
  if (id === null) {
    await insertShortcutGroup(shortcode.trim(), expansion.trim());
  } else {
    await updateShortcutGroup(id, shortcode.trim(), expansion.trim());
  }
  groupDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteGroup = async (id: number) => {
  await deleteShortcutGroup(id);
  await refresh();
  notify('Deleted');
};

const groupHeaders = [
  { title: 'Shortcode', key: 'shortcode' },
  { title: 'Expansion', key: 'expansion' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

</script>

<template>
  <VContainer fluid>
    <VRow justify="center">
      <VCol cols="12" md="10" lg="8" xl="6">
        <VCard variant="outlined" class="pa-4">
          <VCardTitle class="text-h5 mb-2">Settings</VCardTitle>

          <VTabs v-model="tab" class="mb-4">
            <VTab value="mappings">Mappings</VTab>
            <VTab value="listValues">List Values</VTab>
            <VTab value="types">Types</VTab>
            <VTab value="groups">Shortcut Groups</VTab>
          </VTabs>

          <VTabsWindow v-model="tab">

            <!-- Mapping instances -->
            <VTabsWindowItem value="mappings">
              <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddMapping">Add</VBtn>
              <VDataTable :headers="mappingHeaders" :items="mappings" density="compact" :items-per-page="25">
                <template #item.implicit_add_base="{ item }">
                  {{ item.implicit_add_base ? 'Yes' : '' }}
                </template>
                <template #item.actions="{ item }">
                  <VBtn icon="mdi-pencil" size="x-small" variant="text" @click="openEditMapping(item)" />
                  <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click="deleteMapping(item.id)" />
                </template>
              </VDataTable>
            </VTabsWindowItem>

            <!-- List values -->
            <VTabsWindowItem value="listValues">
              <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddListValue">Add</VBtn>
              <VDataTable :headers="listValueHeaders" :items="listValues" density="compact" :items-per-page="25">
                <template #item.actions="{ item }">
                  <VBtn icon="mdi-pencil" size="x-small" variant="text" @click="openEditListValue(item)" />
                  <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click="deleteListVal(item.id)" />
                </template>
              </VDataTable>
            </VTabsWindowItem>

            <!-- Mapping types -->
            <VTabsWindowItem value="types">
              <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddType">Add</VBtn>
              <VDataTable :headers="typeHeaders" :items="mappingTypes" density="compact" :items-per-page="25">
                <template #item.actions="{ item }">
                  <VBtn icon="mdi-pencil" size="x-small" variant="text" @click="openEditType(item)" />
                  <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click="deleteType(item.id)" />
                </template>
              </VDataTable>
            </VTabsWindowItem>

            <!-- Shortcut groups -->
            <VTabsWindowItem value="groups">
              <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddGroup">Add</VBtn>
              <VDataTable :headers="groupHeaders" :items="shortcutGroups" density="compact" :items-per-page="25">
                <template #item.actions="{ item }">
                  <VBtn icon="mdi-pencil" size="x-small" variant="text" @click="openEditGroup(item)" />
                  <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click="deleteGroup(item.id)" />
                </template>
              </VDataTable>
            </VTabsWindowItem>

          </VTabsWindow>
        </VCard>
      </VCol>
    </VRow>
  </VContainer>

  <!-- Mapping dialog -->
  <VDialog v-model="mappingDialog" max-width="520">
    <VCard>
      <VCardTitle>{{ mappingForm.id === null ? 'Add' : 'Edit' }} Mapping</VCardTitle>
      <VCardText class="d-flex flex-column ga-3">
        <VTextField v-model="mappingForm.name" label="Name (e.g. tt<p,>)" density="compact" />
        <VTextField v-model="mappingForm.expansion" label="Expansion (e.g. talked to <p,>)" density="compact" />
        <VCheckbox v-model="mappingForm.implicit_add_base" label="Implicitly add base (e.g. also add 'tt')" density="compact" hide-details />
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4">
        <VBtn variant="text" @click="mappingDialog = false">Cancel</VBtn>
        <VBtn color="primary" @click="saveMapping">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <!-- List value dialog -->
  <VDialog v-model="listValueDialog" max-width="440">
    <VCard>
      <VCardTitle>{{ listValueForm.id === null ? 'Add' : 'Edit' }} List Value</VCardTitle>
      <VCardText class="d-flex flex-column ga-3">
        <VTextField
          v-model="listValueForm.value"
          label="Value (e.g. Lisa)"
          density="compact"
          autofocus
        />
        <VSelect
          v-model="listValueForm.type_id"
          :items="mappingTypes"
          item-title="name"
          item-value="id"
          label="Type"
          density="compact"
        />
        <div class="d-flex align-center ga-2">
          <VTextField
            v-model="listValueForm.abbreviation"
            label="Abbreviation (e.g. li)"
            density="compact"
            :color="abbrevTaken ? 'error' : undefined"
            :base-color="abbrevTaken ? 'error' : undefined"
            :error="abbrevTaken"
            :error-messages="abbrevTaken ? 'Already taken for this type' : undefined"
            hide-details="auto"
            class="flex-grow-1"
            @input="onAbbrevInput"
          />
          <VBtn
            icon="mdi-refresh"
            size="small"
            variant="text"
            title="Regenerate abbreviation"
            @click="regenerateAbbrev"
          />
        </div>
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4">
        <VBtn variant="text" @click="listValueDialog = false">Cancel</VBtn>
        <VBtn color="primary" :disabled="abbrevTaken || !listValueForm.abbreviation || !listValueForm.value" @click="saveListValue">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <!-- Mapping type dialog -->
  <VDialog v-model="typeDialog" max-width="420">
    <VCard>
      <VCardTitle>{{ typeForm.isEdit ? 'Edit' : 'Add' }} Mapping Type</VCardTitle>
      <VCardText class="d-flex flex-column ga-3">
        <VTextField v-model="typeForm.id" label="ID / placeholder (e.g. p, pl, t)" density="compact" :disabled="typeForm.isEdit" />
        <VTextField v-model="typeForm.name" label="Name (e.g. person, place)" density="compact" />
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4">
        <VBtn variant="text" @click="typeDialog = false">Cancel</VBtn>
        <VBtn color="primary" @click="saveType">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <!-- Shortcut group dialog -->
  <VDialog v-model="groupDialog" max-width="520">
    <VCard>
      <VCardTitle>{{ groupForm.id === null ? 'Add' : 'Edit' }} Shortcut Group</VCardTitle>
      <VCardText class="d-flex flex-column ga-3">
        <VTextField v-model="groupForm.shortcode" label="Shortcode (e.g. wd)" density="compact" />
        <VTextField v-model="groupForm.expansion" label="Expansion (full text)" density="compact" />
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4">
        <VBtn variant="text" @click="groupDialog = false">Cancel</VBtn>
        <VBtn color="primary" @click="saveGroup">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <VSnackbar v-model="snackbar" :timeout="1500">{{ snackbarText }}</VSnackbar>
</template>
