<script setup lang="ts">
import { ref, watch, computed, onMounted, useTemplateRef } from 'vue';
import { useRouter } from 'vue-router';
import {
  VContainer, VCard, VCardText, VCardTitle, VTabs, VTab, VTabsWindow, VTabsWindowItem,
  VDataTable, VBtn, VDialog, VTextField, VCheckbox, VSelect,
  VSnackbar, VRow, VCol, VToolbar, VToolbarTitle,
} from 'vuetify/components';
import {
  getMappingInstances, insertMappingInstance, updateMappingInstance, deleteMappingInstance,
  getListValues, insertListValue, updateListValue, deleteListValue,
  getMappingTypes, insertMappingType, updateMappingType, deleteMappingType,
  getShortcutGroups, insertShortcutGroup, updateShortcutGroup, deleteShortcutGroup,
} from '@/lib/db';
import type { MappingInstance, ListValue, MappingType, ShortcutGroup } from '@/lib/db';

const router = useRouter();

const tab = ref('mappings');
const snackbar = ref(false);
const snackbarText = ref('');

const mappings = ref<MappingInstance[]>([]);
const listValues = ref<ListValue[]>([]);
const mappingTypes = ref<MappingType[]>([]);
const shortcutGroups = ref<ShortcutGroup[]>([]);

const refresh = async () => {
  [mappings.value, listValues.value, mappingTypes.value, shortcutGroups.value] = await Promise.all([
    getMappingInstances(),
    getListValues(),
    getMappingTypes(),
    getShortcutGroups(),
  ]);
};

const notify = (msg: string) => {
  snackbarText.value = msg;
  snackbar.value = true;
};

onMounted(refresh);

// ── Mapping instances ────────────────────────────────────────────────────────

const mappingDialog = ref(false);
const mappingForm = ref<{ id: number | null; name: string; expansion: string; addBase: boolean }>({
  id: null, name: '', expansion: '', addBase: false,
});

// Template refs for dialog field navigation
const mappingNameRef = useTemplateRef<InstanceType<any>>('mappingNameRef');
const mappingExpansionRef = useTemplateRef<InstanceType<any>>('mappingExpansionRef');

const openAddMapping = () => {
  mappingForm.value = { id: null, name: '', expansion: '', addBase: false };
  mappingDialog.value = true;
};

const openEditMapping = (row: MappingInstance) => {
  mappingForm.value = { id: row.id, name: row.name, expansion: row.expansion, addBase: false };
  mappingDialog.value = true;
};

const saveMapping = async () => {
  const { id, name, expansion, addBase } = mappingForm.value;
  if (!name.trim() || !expansion.trim()) return;
  if (id === null) {
    await insertMappingInstance(name.trim(), expansion.trim());
    if (addBase) {
      const baseName = name.trim().replace(/<[^>]*>/g, '').trim();
      const baseExpansion = expansion.trim().replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim();
      if (baseName && baseName !== name.trim() && baseExpansion) {
        await insertMappingInstance(baseName, baseExpansion).catch(() => {/* already exists */});
      }
    }
  } else {
    await updateMappingInstance(id, name.trim(), expansion.trim());
  }
  mappingDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteMapping = async (id: number) => {
  await deleteMappingInstance(id);
  await refresh();
  notify('Deleted');
};

const mappingHeaders = [
  { title: 'Name', key: 'name' },
  { title: 'Expansion', key: 'expansion' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

// ── List values ──────────────────────────────────────────────────────────────

/** Generate an abbreviation from a display value. */
function generateAbbreviation(value: string, typeId: string, excludeId: number | null): string {
  const taken = new Set(
    listValues.value
      .filter(v => v.type_id === typeId && v.id !== excludeId)
      .map(v => v.abbreviation.toLowerCase())
  );

  const words = value.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!words.length) return '';

  const chars = words.map(w => w.replace(/[^a-z0-9]/g, '')).join('');

  const initials = words.map(w => w[0] ?? '').join('');
  if (!taken.has(initials)) return initials;

  for (let budget = 2; budget <= Math.min(chars.length, 8); budget++) {
    let candidate = '';
    let remaining = budget;
    for (const word of words) {
      const take = Math.ceil(remaining / (words.length - words.indexOf(word)));
      candidate += word.slice(0, take);
      remaining -= take;
      if (remaining <= 0) break;
    }
    candidate = candidate.slice(0, budget);
    if (!taken.has(candidate)) return candidate;
  }

  for (let i = 2; i < 100; i++) {
    const candidate = initials + i;
    if (!taken.has(candidate)) return candidate;
  }

  return initials;
}

interface ListValueForm {
  id: number | null;
  abbreviation: string;
  value: string;
  type_id: string;
  abbrevAutoGenerated: boolean;
}

const listValueDialog = ref(false);
const listValueForm = ref<ListValueForm>({
  id: null, abbreviation: '', value: '', type_id: '', abbrevAutoGenerated: true,
});

const listValueRef = useTemplateRef<InstanceType<any>>('listValueRef');
const listAbbrevRef = useTemplateRef<InstanceType<any>>('listAbbrevRef');

const abbrevTaken = computed(() => {
  const { abbreviation, type_id, id } = listValueForm.value;
  if (!abbreviation || !type_id) return false;
  return listValues.value.some(
    v => v.type_id === type_id && v.abbreviation.toLowerCase() === abbreviation.toLowerCase() && v.id !== id
  );
});

watch(() => listValueForm.value.value, (val) => {
  if (listValueForm.value.abbrevAutoGenerated) {
    listValueForm.value.abbreviation = generateAbbreviation(val, listValueForm.value.type_id, listValueForm.value.id);
  }
});

watch(() => listValueForm.value.type_id, () => {
  if (listValueForm.value.abbrevAutoGenerated) {
    listValueForm.value.abbreviation = generateAbbreviation(
      listValueForm.value.value, listValueForm.value.type_id, listValueForm.value.id
    );
  }
});

const regenerateAbbrev = () => {
  listValueForm.value.abbreviation = generateAbbreviation(
    listValueForm.value.value, listValueForm.value.type_id, listValueForm.value.id
  );
  listValueForm.value.abbrevAutoGenerated = true;
};

const onAbbrevInput = () => {
  listValueForm.value.abbrevAutoGenerated = false;
};

const openAddListValue = () => {
  listValueForm.value = { id: null, abbreviation: '', value: '', type_id: '', abbrevAutoGenerated: true };
  listValueDialog.value = true;
};

const openEditListValue = (row: ListValue) => {
  listValueForm.value = {
    id: row.id,
    abbreviation: row.abbreviation,
    value: row.value,
    type_id: row.type_id,
    abbrevAutoGenerated: false,
  };
  listValueDialog.value = true;
};

const saveListValue = async () => {
  const { id, abbreviation, value, type_id } = listValueForm.value;
  if (!value.trim() || abbrevTaken.value) return;
  const abbrev = abbreviation.trim() || undefined;
  if (id === null) {
    await insertListValue(value.trim(), type_id.trim(), abbrev);
  } else {
    await updateListValue(id, value.trim(), type_id.trim(), abbrev);
  }
  listValueDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteListVal = async (id: number) => {
  await deleteListValue(id);
  await refresh();
  notify('Deleted');
};

const listValueHeaders = [
  { title: 'Abbreviation', key: 'abbreviation' },
  { title: 'Value', key: 'value' },
  { title: 'Type', key: 'type_id' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

// ── Mapping types ────────────────────────────────────────────────────────────

const typeDialog = ref(false);
const typeForm = ref<{ id: string; name: string; isEdit: boolean }>({ id: '', name: '', isEdit: false });

const typeIdRef = useTemplateRef<InstanceType<any>>('typeIdRef');
const typeNameRef = useTemplateRef<InstanceType<any>>('typeNameRef');

const openAddType = () => {
  typeForm.value = { id: '', name: '', isEdit: false };
  typeDialog.value = true;
};

const openEditType = (row: MappingType) => {
  typeForm.value = { id: row.id, name: row.name, isEdit: true };
  typeDialog.value = true;
};

const saveType = async () => {
  const { id, name, isEdit } = typeForm.value;
  if (!id.trim() || !name.trim()) return;
  if (isEdit) {
    await updateMappingType(id.trim(), name.trim());
  } else {
    await insertMappingType(id.trim(), name.trim());
  }
  typeDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteType = async (id: string) => {
  await deleteMappingType(id);
  await refresh();
  notify('Deleted');
};

const typeHeaders = [
  { title: 'ID (placeholder)', key: 'id' },
  { title: 'Name', key: 'name' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

// ── Shortcut groups ──────────────────────────────────────────────────────────

const groupDialog = ref(false);
const groupForm = ref<{ id: number | null; shortcode: string; expansion: string }>({
  id: null, shortcode: '', expansion: '',
});

const groupShortcodeRef = useTemplateRef<InstanceType<any>>('groupShortcodeRef');
const groupExpansionRef = useTemplateRef<InstanceType<any>>('groupExpansionRef');

const openAddGroup = () => {
  groupForm.value = { id: null, shortcode: '', expansion: '' };
  groupDialog.value = true;
};

const openEditGroup = (row: ShortcutGroup) => {
  groupForm.value = { id: row.id, shortcode: row.shortcode, expansion: row.expansion };
  groupDialog.value = true;
};

const saveGroup = async () => {
  const { id, shortcode, expansion } = groupForm.value;
  if (!shortcode.trim() || !expansion.trim()) return;
  if (id === null) {
    await insertShortcutGroup(shortcode.trim(), expansion.trim());
  } else {
    await updateShortcutGroup(id, shortcode.trim(), expansion.trim());
  }
  groupDialog.value = false;
  await refresh();
  notify('Saved');
};

const deleteGroup = async (id: number) => {
  await deleteShortcutGroup(id);
  await refresh();
  notify('Deleted');
};

const groupHeaders = [
  { title: 'Shortcode', key: 'shortcode' },
  { title: 'Expansion', key: 'expansion' },
  { title: '', key: 'actions', sortable: false, align: 'end' as const },
];

</script>

<template>
  <VContainer fluid class="pa-0 pa-sm-4">

    <!-- Header bar with back button -->
    <VRow no-gutters align="center" class="mb-2 px-2 px-sm-0">
      <VBtn
        icon="mdi-arrow-left"
        variant="text"
        @click="router.push('/')"
        aria-label="Back"
      />
      <span class="text-h6 ml-2">Settings</span>
    </VRow>

    <VCard variant="outlined">
      <VTabs v-model="tab" class="mb-2">
        <VTab value="mappings">Mappings</VTab>
        <VTab value="listValues">List Values</VTab>
        <VTab value="types">Types</VTab>
        <VTab value="groups">Shortcut Groups</VTab>
      </VTabs>

      <VCardText class="pa-2 pa-sm-4">
        <VTabsWindow v-model="tab">

          <!-- Mapping instances -->
          <VTabsWindowItem value="mappings">
            <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddMapping">Add</VBtn>
            <VDataTable
              :headers="mappingHeaders"
              :items="mappings"
              density="compact"
              :items-per-page="-1"
              hover
              @click:row="(_: any, { item }: any) => openEditMapping(item)"
              style="cursor: pointer"
            >
              <template #item.actions="{ item }">
                <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click.stop="deleteMapping(item.id)" />
              </template>
              <template #bottom />
            </VDataTable>
          </VTabsWindowItem>

          <!-- List values -->
          <VTabsWindowItem value="listValues">
            <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddListValue">Add</VBtn>
            <VDataTable
              :headers="listValueHeaders"
              :items="listValues"
              density="compact"
              :items-per-page="-1"
              hover
              @click:row="(_: any, { item }: any) => openEditListValue(item)"
              style="cursor: pointer"
            >
              <template #item.actions="{ item }">
                <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click.stop="deleteListVal(item.id)" />
              </template>
              <template #bottom />
            </VDataTable>
          </VTabsWindowItem>

          <!-- Mapping types -->
          <VTabsWindowItem value="types">
            <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddType">Add</VBtn>
            <VDataTable
              :headers="typeHeaders"
              :items="mappingTypes"
              density="compact"
              :items-per-page="-1"
              hover
              @click:row="(_: any, { item }: any) => openEditType(item)"
              style="cursor: pointer"
            >
              <template #item.actions="{ item }">
                <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click.stop="deleteType(item.id)" />
              </template>
              <template #bottom />
            </VDataTable>
          </VTabsWindowItem>

          <!-- Shortcut groups -->
          <VTabsWindowItem value="groups">
            <VBtn size="small" prepend-icon="mdi-plus" class="mb-3" @click="openAddGroup">Add</VBtn>
            <VDataTable
              :headers="groupHeaders"
              :items="shortcutGroups"
              density="compact"
              :items-per-page="-1"
              hover
              @click:row="(_: any, { item }: any) => openEditGroup(item)"
              style="cursor: pointer"
            >
              <template #item.actions="{ item }">
                <VBtn icon="mdi-delete" size="x-small" variant="text" color="error" @click.stop="deleteGroup(item.id)" />
              </template>
              <template #bottom />
            </VDataTable>
          </VTabsWindowItem>

        </VTabsWindow>
      </VCardText>
    </VCard>
  </VContainer>

  <!-- Mapping dialog -->
  <VDialog v-model="mappingDialog" max-width="520" :fullscreen="false" :scrim="true">
    <VCard>
      <VCardTitle class="pa-4">{{ mappingForm.id === null ? 'Add' : 'Edit' }} Mapping</VCardTitle>
      <VCardText class="d-flex flex-column ga-3 pt-0">
        <VTextField
          ref="mappingNameRef"
          v-model="mappingForm.name"
          label="Name (e.g. tt<p,>)"
          density="compact"
          autofocus
          @keydown.enter.prevent="mappingExpansionRef?.focus()"
        />
        <VTextField
          ref="mappingExpansionRef"
          v-model="mappingForm.expansion"
          label="Expansion (e.g. talked to <p,>)"
          density="compact"
          @keydown.enter.prevent="saveMapping"
        />
        <VCheckbox
          v-if="mappingForm.id === null"
          v-model="mappingForm.addBase"
          label="Also add base (e.g. also insert 'tt' → 'talked to')"
          density="compact"
          hide-details
        />
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4 pt-2">
        <VBtn variant="text" @click="mappingDialog = false">Cancel</VBtn>
        <VBtn color="primary" @click="saveMapping">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <!-- List value dialog -->
  <VDialog v-model="listValueDialog" max-width="440">
    <VCard>
      <VCardTitle class="pa-4">{{ listValueForm.id === null ? 'Add' : 'Edit' }} List Value</VCardTitle>
      <VCardText class="d-flex flex-column ga-3 pt-0">
        <VTextField
          ref="listValueRef"
          v-model="listValueForm.value"
          label="Value (e.g. Lisa)"
          density="compact"
          autofocus
          @keydown.enter.prevent="listAbbrevRef?.focus()"
        />
        <VSelect
          v-model="listValueForm.type_id"
          :items="mappingTypes"
          item-title="name"
          item-value="id"
          label="Type"
          density="compact"
        />
        <div class="d-flex align-center ga-2">
          <VTextField
            ref="listAbbrevRef"
            v-model="listValueForm.abbreviation"
            label="Abbreviation (e.g. li)"
            density="compact"
            :color="abbrevTaken ? 'error' : undefined"
            :base-color="abbrevTaken ? 'error' : undefined"
            :error="abbrevTaken"
            :error-messages="abbrevTaken ? 'Already taken for this type' : undefined"
            hide-details="auto"
            class="flex-grow-1"
            @input="onAbbrevInput"
            @keydown.enter.prevent="saveListValue"
          />
          <VBtn
            icon="mdi-refresh"
            size="small"
            variant="text"
            title="Regenerate abbreviation"
            @click="regenerateAbbrev"
          />
        </div>
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4 pt-2">
        <VBtn variant="text" @click="listValueDialog = false">Cancel</VBtn>
        <VBtn color="primary" :disabled="abbrevTaken || !listValueForm.value" @click="saveListValue">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <!-- Mapping type dialog -->
  <VDialog v-model="typeDialog" max-width="420">
    <VCard>
      <VCardTitle class="pa-4">{{ typeForm.isEdit ? 'Edit' : 'Add' }} Mapping Type</VCardTitle>
      <VCardText class="d-flex flex-column ga-3 pt-0">
        <VTextField
          ref="typeIdRef"
          v-model="typeForm.id"
          label="ID / placeholder (e.g. p, pl, t)"
          density="compact"
          :disabled="typeForm.isEdit"
          autofocus
          @keydown.enter.prevent="typeNameRef?.focus()"
        />
        <VTextField
          ref="typeNameRef"
          v-model="typeForm.name"
          label="Name (e.g. person, place)"
          density="compact"
          @keydown.enter.prevent="saveType"
        />
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4 pt-2">
        <VBtn variant="text" @click="typeDialog = false">Cancel</VBtn>
        <VBtn color="primary" @click="saveType">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <!-- Shortcut group dialog -->
  <VDialog v-model="groupDialog" max-width="520">
    <VCard>
      <VCardTitle class="pa-4">{{ groupForm.id === null ? 'Add' : 'Edit' }} Shortcut Group</VCardTitle>
      <VCardText class="d-flex flex-column ga-3 pt-0">
        <VTextField
          ref="groupShortcodeRef"
          v-model="groupForm.shortcode"
          label="Shortcode (e.g. wd)"
          density="compact"
          autofocus
          @keydown.enter.prevent="groupExpansionRef?.focus()"
        />
        <!-- Expansion is multiline — Enter adds a newline, not submits -->
        <VTextField
          ref="groupExpansionRef"
          v-model="groupForm.expansion"
          label="Expansion (full text)"
          density="compact"
        />
      </VCardText>
      <div class="d-flex justify-end ga-2 pa-4 pt-2">
        <VBtn variant="text" @click="groupDialog = false">Cancel</VBtn>
        <VBtn color="primary" @click="saveGroup">Save</VBtn>
      </div>
    </VCard>
  </VDialog>

  <VSnackbar v-model="snackbar" :timeout="1500">{{ snackbarText }}</VSnackbar>
</template>
